### ISSUE TITLE
update chromedriver to V98 on all core-npm packages

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-npm#452]
Chrome 98 was released recently, ChromeDriver needs to be updated to match in our packages need to be updated accordingly. 

See: 
https://github.com/dequelabs/axe-core-npm/issues/401
https://github.com/dequelabs/axe-core-npm/issues/450

**Comment by Zidious** [comment]
Update to always use `latest` ChromeDriver on all packages: 

- [ ] CLI
- [ ] Playwright
- [ ] Puppeteer
- [ ] React
- [ ] WebdriverIO
- [ ] WebdriverJS

**Comment by padmavemulapati** [comment]
Validated as part of `axe-core-npm` QA, 
Chromedriver was always installing as a dependency, but now it's using `latest` instead of us pinning a `chromedriver` version. 
For Example:
Prior to change:
if a user has Chrome V97, our package was pinned to V95 chrome driver, this would break CLI
New change:
If a user install CLI it will install latest chromedriver (say V99) their browser needs to be fully up to date
