### ISSUE TITLE
Depend on playwright-core rather on playwright

### ISSUE THREAD

**Issue by mxschmitt** [dequelabs/axe-core-npm#536]
Currently axe playwright depends on playwright. This means that if you install axe playwright, that all browsers get automatically downloaded, since we download the browsers in the postinstall step.

Since around half a year or so, playwright depends on playwright-core and @playwright/test depends on playwright-core.

I'd recommend to also depend on playwright-core instead, which will give you the correct types, but keep the flexibility up to the user which browser he wants to install. Also @playwright/test does not install all the browsers anymore, you need to explicitly call npx playwright install to install them or just one of them.

See here: https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/package.json

**Comment by michael-siek** [comment]
Hey @mxschmitt

Thank you for submitting the recommendation we will discuss this and update the package as needed.

**Comment by padmavemulapati** [comment]
Validated this using `@axe-core/playwright-4.4.5-alpha.313` 
Here while validating, instead of installing `playwright`, installed `playwright-core_1.25.2` (so `playwright-` not exists in the dependencies list)
Run the `js` script
```
const AxeBuilder = require('@axe-core/playwright').default;
const playwright = require('playwright-core');

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://dequeuniversity.com/demo/mars/');

  try {
    const results = await new AxeBuilder({ page }).analyze();
    console.log(results);
  } catch (e) {
    // do something with the error
  }
  await browser.close();
})();
```
and it is giving expected results holding `axe-core_4.4.3`
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/47409579/190981027-0347fe35-a7b4-4663-b76f-ee60b4766073.png">

But here observed one thing:
Even If I pass `const playwright = require('playwright'); ` instead of `const playwright = require('playwright-core');` seeing the expected results.
