### ISSUE TITLE
webdriverio: Update to latest webdriverio

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#829]
As part of [the conversion to npm workspaces](https://github.com/dequelabs/axe-core-npm/pull/687) we had to [pin the version of Webdriverio](https://github.com/dequelabs/axe-core-npm/pull/687#discussion_r1322081470) as the latest version causes type errors. Need to spend time updating the types.

**Comment by dbjorge** [comment]
Notably, this will including updating the package to rely on the `Browser`/`Element` types from the global `WebdriverIO.*` type namespace, rather than the ones exported from the index of the `webdriverio` package - the latter was deprecated in https://github.com/webdriverio/webdriverio/commit/2a66834912741fbc583e7f544571ce1d6cb0dfcc and is expected to be removed in webdriverio v9.

We'll need to test how to make that cooperate with back-compat for old webdriverio versions we support - I suspect it might involve type shenanigans like `Awaited<ReturnType<webdriverio.remote>> | WebdriverIO.Browser`.

**Comment by 2erix** [comment]
We are now impacted in our organisation because the AxeBuilder requires deprecated interface `Browser` type from npm package/path `WebdriverIO/build/types` which we use as browser/driver in our projects. 

WDIO now supplies browser/driver types from  package/path `@wdio/globals/types` as `WebdriverIO.Browser` instead. 

Currently we don’t have any solution except wait for an update to AxeBuilder, so anything that could be expedited would be helpful. 

In the meantime I am using the deprecated type at risk.

**Comment by padmavemulapati** [comment]
Verified with the latest Canary version - `4.8.3-6b60442.0` and with typescript- webdriverio is working as expected. Validated with V8, V7 and  V6 . With all the versions typescript is working fine.

Steps validated:
1. installed @axe-core/webdriverio package in webdriverio (5.3.3 , v6.12.1, v7.34.0, v8.21.0, and @wdio/cli- v8.24.2,
    @wdio/globals-8.24.2 ) 
 

Test code: compile and run using typescript 
```

import { AxeBuilder } from '@axe-core/webdriverio'
import { remote } from 'webdriverio'

(async () => {
  const client = await remote({
    logLevel: 'error',
    capabilities: {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['headless', 'disable-gpu']
      }
    }
  })
  await client.url('https://dequeuniversity.com/demo/mars/')

  try {
    const results = await new AxeBuilder({ client }).analyze()
    console.log(results)
  } catch (e) {
    console.error(e)
  }

  client.deleteSession()
})()

```
wdio.conf.ts

```
import { Config } from '@wdio/types';

export const config: Config = {
    
  // Your WebDriverIO configuration here
};
```

<details> 
<summary> V8 working recording </summary>

https://github.com/dequelabs/axe-core-npm/assets/47409579/16c8e953-5514-42a7-8f91-190169983e9f


</details>

<details> 
<summary> V7 working recording </summary>


https://github.com/dequelabs/axe-core-npm/assets/47409579/f8596d37-10ad-48ad-b0c1-1555ce74d035



</details>

<details> 
<summary> V6 working recording </summary>


https://github.com/dequelabs/axe-core-npm/assets/47409579/eb0fb13f-7467-4109-8c5f-f309f9f69a6d



</details>


Note: For webdriverio v5, the code above should compile but may not open a browser and run. This is a set up issue with the webdriverio and not our code so we are OK if the builds but doesn't run in v5.

When trying to run using V5 getting error:

```
2024-01-12T13:02:04.277Z ERROR webdriver: Request failed due to AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-01-12T13:02:04.279Z ERROR webdriver: AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
/Users/dq_user/Documents/CoreWDIO/node_modules/webdriverio/node_modules/webdriver/build/utils.js:45
    throw new Error('Failed to create session.\n' + message);
          ^
Error: Failed to create session.
Unable to connect to "undefined:undefined", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file.
    at startWebDriverSession (/Users/dq_user/Documents/CoreWDIO/node_modules/webdriverio/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.newSession (/Users/dq_user/Documents/CoreWDIO/node_modules/webdriverio/node_modules/webdriver/build/index.js:46:23)
    at async remote (/Users/dq_user/Documents/CoreWDIO/node_modules/webdriverio/build/index.js:55:20)
```
which is expected.

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core/webdriverio_ |
|**Version** | _4.8.3-6b60442.0_ |
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129   & Firefox 121.0_| (edited)
