### ISSUE TITLE
Pin axe-core version to patch updates only (`~`)

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#837]
A user recently ran into a problem where [they installed an api at v4.7](https://github.com/dequelabs/axe-core-npm/issues/830) but got axe-core version v4.8 (causing some confusion on why rules weren't running that should have been). Turns out that we've been pinning to axe-core using `^` which allows minor updates. This goes against our goal of version locking the apis to the major and minor version of axe-core that is used in the api. 

We'll fix this by using `~` to patch pin our axe-core dependency.

**Comment by padmavemulapati** [comment]
Here validated the scenarios:
1. With Production version of axe-core-npm packages(4.7.0), holding a axe-core version 4.7.2 (old version) with `^` in dependencies.

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/79f8cf91-84e7-44ee-b366-3bf250a4124e)

in the output it is getting the axe-core version with latest axe-core(4.8.2) because of the dependency specified as `^` so it allowing the next to 4.7.2 all minor versions.

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/450a9e03-3ef6-48af-9b33-b0e4ba4ddfdc)

2. With Production version of axe-core-npm pacakges(4.7.0), holding a axe-core version 4.7.2(old version) without `^` in the dependencies.
<img width="452" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/a56790a9-ed1c-4c18-874f-e1e5bdb11224">

in the output it is getting the axe-core version with  (4.7.2) because of the dependency specified without `^`  it is strictly considering the specified version and not allowing the next to 4.7.2 all minor versions.

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/7f3df09d-880b-4484-8eba-781aba68bcde)

3. With the latest canary version of axe-core-npm packages(4.7.4-f03670b.0), and  with  (4.7.2) because of the dependency specified without `^`  it is strictly considering the specified version and not allowing the next to 4.7.2 all minor versions.

<img width="459" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/a176b4bf-33a5-4231-945d-c0635b1129d9">

in the output it is getting the axe-core version with  (4.7.2) because of the dependency specified without `^`  it is strictly considering the specified version and not allowing the next to 4.7.2 all minor versions.

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/72db0172-0443-4ccb-9290-c69cdaf0f793)

4.  With the latest canary version of axe-core-npm packages(4.7.4-f03670b.0) , and  with latest (4.8.2) because of the dependency specified without `^`  it is strictly considering the specified version and not allowing the next to 4.8.2 all minor versions.

<img width="463" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/abe15855-77a4-41c1-9f42-fa80335472dd">

in the output it is getting the axe-core version with  (4.8.2) because of the dependency specified without `^`  it is strictly considering the specified version and not allowing the next to 4.8.2 all minor versions.

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/53ce24af-b18a-446f-b4b6-303e7f25ae52)
