### ISSUE TITLE
axe-core-npm v4.8.1

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#866]
Below is everything related to this release

### !!!!!!!!!! DEPENDENCIES / BLOCKERS !!!!!!!!!!
None

### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```[tasklist]
### Links
- [x] Release candidate PR: https://github.com/dequelabs/axe-core-npm/pull/865
- [ ] Release PR:
- [ ] Release audit:
```

## Steps
- [x] Requested QA
- [ ] QA signoff on RC
- [ ] Release created
- [ ] Release audit done
- [ ] Release audit posted
- [ ] Release merged
- [ ] Deployed
- [ ] Posted in product-channel

## Additional Steps For AWS Deploys
- [x] AWS NOT NEEDED
- [ ] Emailed IHD
- [ ] Set up meeting for deployment
- [ ] Data migrations:
- [ ] Environment variables:
- [ ] Docker image:
- [ ] Smoke test passed

## Additional Steps Release Notes
- [x] RELEASE NOTES NOT NEEDED
- [ ] Ticket created for release notes: (URL here)
- [ ] Release notes reviewed
- [ ] Release notes published 
- [ ] Release notes: (public URL)

**Comment by padmavemulapati** [comment]
[One issue](https://github.com/dequelabs/axe-core-npm/issues/852), reopened, but this is working fine. Re-opened it to ensure the fix is working properly for the end-users. Will close once @axe-core/cli@4.8.1 is released and tested by the users.
Another low-priority issue is still open (https://github.com/dequelabs/axe-core-npm/issues/857), but not a blocker for the release on build - 4.8.1-5bfd440.0  

We are good to go with the Build- `axe-core-npm_4.8.1-5bfd440.0`

Please find the [Test plan](https://dequeqa.testrail.io/index.php?/plans/view/2269) here and credentials to access are mentioned in the sign-off email communication
